(function(){'use strict';
const load=(src)=>new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.body.appendChild(s)});
function norm(s){return String(s||'').normalize('NFC').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
async function boot(){await load('v18.js?engine=stable-v31');const input=document.getElementById('files');if(!input)return;const libUrl='integration-library-2026-2027.json?cb='+Date.now();let lib=null,curr=null;try{lib=await (await fetch(libUrl,{cache:'no-store'})).json();}catch(e){}try{curr=await (await fetch('curriculum-adjustments-2026-2027.json?cb='+Date.now(),{cache:'no-store'})).json();}catch(e){}
const keywordMap={NLS:['canva','powerpoint','internet','tìm kiếm','poster','nguồn số','công cụ số'],CONG_DAN_SO:['mạng xã hội','bản quyền','dữ liệu cá nhân','nguồn tin','kiểm chứng','an toàn tài khoản'],HCM:['bác hồ','hồ chí minh','yêu nước','đoàn kết','tiết kiệm','giản dị','trách nhiệm'],MOI_TRUONG_BDKH:['môi trường','rác','tái chế','đất','nước','khí hậu','đa dạng sinh học','năng lượng'],NUOC:['nước sạch','nước ngầm','ao','hồ','sông','kênh','tiết kiệm nước'],BIEN_DAO:['biển','đảo','hoàng sa','trường sa','ven biển','đại dương','tài nguyên biển'],BIEN_GIOI:['biên giới','lãnh thổ','chủ quyền','quốc giới','quần đảo'],GIAO_THONG:['giao thông','xe đạp','mũ bảo hiểm','biển báo','qua đường','đi bộ'],DUOI_NUOC:['đuối nước','bơi','sông','hồ','ao','lũ','an toàn'],QUYEN_TRE_EM:['quyền trẻ em','bảo vệ trẻ em','bày tỏ ý kiến','không bạo lực','tôn trọng trẻ'],BINH_DANG:['bình đẳng','giới','hòa nhập','khuyết tật','khác biệt'],TAI_CHINH:['tiền','mua','bán','giá','chi tiêu','tiêu dùng','ngân sách'],STEM:['thiết kế','thử nghiệm','mô hình','chế tạo','vật liệu','cải tiến'],PHAP_LUAT:['pháp luật','quy định','nghĩa vụ','quyền','luật'],SUC_KHOE:['sức khỏe','vệ sinh','dinh dưỡng','thực phẩm','bệnh','rửa tay'],THIEN_TAI:['bão','lũ','lũ quét','sạt lở','hạn hán','thiên tai','cảnh báo'],VAN_HOA:['di sản','di tích','truyền thống','văn hóa','lễ hội','làng nghề'],AI:['ai','chatgpt','gemini','kiểm chứng','thông tin sai','đánh giá thông tin']};
function afterAnalyze(){setTimeout(()=>{const S=window.S;if(!S?.docs?.length)return;const texts=S.docs.map(d=>({name:d.name,text:norm(d.text||window.xmlText?.(d.xml)||'')}));const cats=(lib?.categories||[]).map(c=>({id:c.id,name:c.name,keys:keywordMap[c.id]||[],hits:[]}));for(const c of cats)for(const d of texts)for(const k of c.keys)if(d.text.includes(norm(k))&&!c.hits.some(h=>h.file===d.name&&h.k===k))c.hits.push({file:d.name,k});S.integration=cats.map(c=>({id:c.id,name:c.name,hits:[...new Set(c.hits.map(h=>h.k))],status:c.hits.length?'ĐÃ CÓ DẤU HIỆU':'CẦN XEM XÉT',suggest:(lib?.categories||[]).find(x=>x.id===c.id)?.rule||''}));if(typeof window.renderIntegration==='function')window.renderIntegration();
if(curr?.subjects){const extra=[];for(const [sub,arr] of Object.entries(curr.subjects))for(const r of arr||[])if(r.old&&r.new)for(const d of texts){if(d.text.includes(norm(r.old))&&!S.changes.some(x=>x.id===r.id&&x.location===d.name))extra.push({id:r.id,engine:'Curriculum Adjustment Engine',status:'PROPOSED',old_text:r.old,new_text:r.new,location:d.name,confidence:'HIGH',reason:'Khớp danh mục điều chỉnh SGK 2026–2027',ui:''})}S.changes=[...extra,...S.changes.filter(x=>!extra.some(y=>y.id===x.id&&y.location===x.location))];if(typeof window.renderChanges==='function')window.renderChanges();if(typeof window.stats==='function')window.stats()}
},350)}
input.addEventListener('change',afterAnalyze);const analyze=document.getElementById('analyze');if(analyze)analyze.addEventListener('click',afterAnalyze);const oldStart=window.startEditor;window.startEditor=function(){if(typeof oldStart==='function')oldStart();afterAnalyze()};
const ai=document.getElementById('runAi');if(ai)ai.addEventListener('click',()=>setTimeout(afterAnalyze,900));}
boot().catch(()=>{});
})();
