from pathlib import Path

p=Path('sua-giao-an/v60.html')
s=p.read_text(encoding='utf-8')

old="""function replaceRun(xml,c){return false;}function appendRun(xml,c){return false;}function validate(d,c){const p=pars(d.parts[c.part])[c.paragraphIndex];if(!p)return false;return c.type==='INTEGRATION'?norm(p.text).includes(norm(c.insertText)):norm(p.text).includes(norm(c.new))&&!norm(p.text).includes(norm(c.anchor))}$('apply').onclick=()=>{let ok=0,fail=[];for(const d of S.docs)for(const c of S.changes.filter(x=>x.approved&&!x.rejected&&x.document===d.name).sort((a,b)=>(b.matchStart||0)-(a.matchStart||0))){const r=c.type==='INTEGRATION'?appendRun(d.parts[c.part],c):replaceRun(d.parts[c.part],c);if(!r.ok){fail.push(c.id+': '+c.reason);continue}d.parts[c.part]=r.xml;c.applied=true;ok++}"""

new="""function __v60SafeXmlEdit(xml,c,mode){try{const d=parseXml(xml),ps=[...d.getElementsByTagNameNS(W,'p')],p=ps[c.paragraphIndex];if(!p)return{ok:false,reason:'Không tìm thấy paragraph '+(c.paragraphIndex+1)+'.'};const ts=[...p.getElementsByTagNameNS(W,'t')],text=ts.map(t=>t.textContent||'').join('');if(mode==='INSERT_AFTER'){const r=styled(d,null,String(c.insertText||''));p.appendChild(r)}else{const anchor=String(c.anchor||c.old_text||''),replacement=String(c.new||c.new_text||'');const idx=text.indexOf(anchor);if(idx<0)return{ok:false,reason:'Anchor không còn tồn tại.'};const end=idx+anchor.length;let pos=0,si=-1,ei=-1,so=0,eo=0;for(let i=0;i<ts.length;i++){const n=pos+(ts[i].textContent||'').length;if(si<0&&idx>=pos&&idx<n){si=i;so=idx-pos}if(end>pos&&end<=n){ei=i;eo=end-pos;break}pos=n}if(si<0||ei<0)return{ok:false,reason:'Không xác định được vùng Anchor.'};const vals=ts.map(t=>t.textContent||'');if(mode==='DELETE')replacement='';vals[si]=vals[si].slice(0,so)+replacement+vals[si].slice(eo);for(let i=si+1;i<=ei;i++)vals[i]=i===ei?vals[i].slice(eo):'';for(let i=ts.length-1;i>=0;i--){const t=ts[i],v=vals[i];while(t.firstChild)t.removeChild(t.firstChild);t.textContent=v}}return{ok:true,xml:new XMLSerializer().serializeToString(d)}}catch(e){return{ok:false,reason:e&&e.message?e.message:String(e)}}}function replaceRun(xml,c){return __v60SafeXmlEdit(xml,c,'REPLACE')}function appendRun(xml,c){return __v60SafeXmlEdit(xml,c,'INSERT_AFTER')}function validate(d,c){const p=pars(d.parts[c.part])[c.paragraphIndex];if(!p)return false;return c.type==='INTEGRATION'?norm(p.text).includes(norm(c.insertText)):norm(p.text).includes(norm(c.new))&&!norm(p.text).includes(norm(c.anchor))}$('apply').onclick=()=>{let ok=0,fail=[];S.applied=false;for(const d of S.docs)for(const c of S.changes.filter(x=>x.approved&&!x.rejected&&x.document===d.name).sort((a,b)=>(b.matchStart||0)-(a.matchStart||0))){const r=c.type==='INTEGRATION'?appendRun(d.parts[c.part],c):replaceRun(d.parts[c.part],c);if(!r.ok){fail.push(c.id+': '+r.reason);continue}d.parts[c.part]=r.xml;c.applied=true;ok++;}S.applied=ok>0;"""

if old not in s:
    raise SystemExit('OLD_RUNTIME_APPLY_BLOCK_NOT_FOUND')
s=s.replace(old,new,1)
if 'insertBefore(' in s[s.find('function __v60SafeXmlEdit'):s.find("$('gemTest')")]:
    raise SystemExit('UNSAFE_INSERTBEFORE_FOUND_IN_RUNTIME_PATCH')
p.write_text(s,encoding='utf-8')
print('HARD_RUNTIME_PATCH_OK',len(s))